//! Qiskit Python code generation for quantum circuits.
//!
//! This module exports KetGrid circuits to Python code that can be executed
//! with Qiskit's QuantumCircuit API.

use crate::circuit::{Circuit, Measurement, PlacedGate};
use crate::gate::GateType;

/// Error type for Qiskit export operations.
#[derive(Debug, Clone, PartialEq)]
pub enum QiskitError {
    /// Circuit has no qubits.
    EmptyCircuit,
    /// Invalid gate configuration.
    InvalidGate(String),
}

impl std::fmt::Display for QiskitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            QiskitError::EmptyCircuit => write!(f, "Cannot export empty circuit (no qubits)"),
            QiskitError::InvalidGate(msg) => write!(f, "Invalid gate configuration: {}", msg),
        }
    }
}

impl std::error::Error for QiskitError {}

/// Generate Qiskit Python code for a circuit.
///
/// The generated code creates a QuantumCircuit with the appropriate number of
/// qubits and classical bits, then applies all gates in execution order.
///
/// # Arguments
/// * `circuit` - The circuit to export.
///
/// # Returns
/// * `Ok(String)` - The generated Python code.
/// * `Err(QiskitError)` - If the circuit cannot be exported.
///
/// # Example
/// ```
/// use ketgrid_core::{Circuit, GateType};
/// use ketgrid_core::format::qiskit::circuit_to_qiskit;
///
/// let mut circuit = Circuit::new(2);
/// circuit.add_gate(GateType::H, vec![0], vec![], 0).unwrap();
/// circuit.add_gate(GateType::Cnot, vec![1], vec![0], 1).unwrap();
///
/// let python_code = circuit_to_qiskit(&circuit).unwrap();
/// assert!(python_code.contains("QuantumCircuit"));
/// assert!(python_code.contains("qc.h(0)"));
/// assert!(python_code.contains("qc.cx(0, 1)"));
/// ```
pub fn circuit_to_qiskit(circuit: &Circuit) -> Result<String, QiskitError> {
    if circuit.num_qubits() == 0 {
        return Err(QiskitError::EmptyCircuit);
    }

    let mut lines = Vec::new();

    // Header
    lines.push("# Generated by KetGrid - Qiskit QuantumCircuit export".to_string());
    lines.push(String::new());
    lines.push("from qiskit import QuantumCircuit".to_string());
    lines.push(String::new());

    // Count measurements to determine classical bits needed
    let num_measurements = circuit.measurements.len();
    let num_qubits = circuit.num_qubits();

    // Circuit initialization
    if num_measurements > 0 {
        lines.push(format!(
            "qc = QuantumCircuit({}, {})  # {} qubits, {} classical bits",
            num_qubits, num_measurements, num_qubits, num_measurements
        ));
    } else {
        lines.push(format!(
            "qc = QuantumCircuit({})  # {} qubits",
            num_qubits, num_qubits
        ));
    }
    lines.push(String::new());

    // Get gates sorted by column (execution order)
    let sorted_gates = circuit.gates_by_column();

    // Generate gate code
    for gate in sorted_gates {
        if let Some(gate_line) = generate_gate_code(gate) {
            lines.push(gate_line);
        }
    }

    // Generate measurement code
    if !circuit.measurements.is_empty() {
        lines.push(String::new());
        lines.push("# Measurements".to_string());

        // Sort measurements by column for consistent ordering
        let mut sorted_measurements: Vec<&Measurement> =
            circuit.measurements.iter().collect();
        sorted_measurements.sort_by_key(|m| m.column);

        for (idx, measurement) in sorted_measurements.iter().enumerate() {
            lines.push(format!(
                "qc.measure({}, {})  # Measure qubit {} to classical bit {}",
                measurement.qubit_id, idx, measurement.qubit_id, idx
            ));
        }
    }

    lines.push(String::new());
    lines.push("# Run the circuit".to_string());
    lines.push("# from qiskit import transpile, Aer".to_string());
    lines.push("# simulator = Aer.get_backend('aer_simulator')".to_string());
    lines.push("# compiled = transpile(qc, simulator)".to_string());
    lines.push("# result = simulator.run(compiled).result()".to_string());
    lines.push("# print(result.get_counts())".to_string());

    Ok(lines.join("\n"))
}

/// Generate Python code for a single gate.
///
/// Returns `Some(String)` with the code line, or `None` if the gate
/// should be skipped (e.g., Identity gates).
fn generate_gate_code(gate: &PlacedGate) -> Option<String> {
    match &gate.gate {
        // Single-qubit gates (no parameters)
        GateType::H => {
            let target = gate.target_qubits.first()?;
            Some(format!("qc.h({})", target))
        }
        GateType::X => {
            let target = gate.target_qubits.first()?;
            Some(format!("qc.x({})", target))
        }
        GateType::Y => {
            let target = gate.target_qubits.first()?;
            Some(format!("qc.y({})", target))
        }
        GateType::Z => {
            let target = gate.target_qubits.first()?;
            Some(format!("qc.z({})", target))
        }
        GateType::S => {
            let target = gate.target_qubits.first()?;
            Some(format!("qc.s({})", target))
        }
        GateType::T => {
            let target = gate.target_qubits.first()?;
            Some(format!("qc.t({})", target))
        }

        // Parameterized single-qubit gates
        GateType::Rx(theta) => {
            let target = gate.target_qubits.first()?;
            Some(format!("qc.rx({:.6}, {})", theta, target))
        }
        GateType::Ry(theta) => {
            let target = gate.target_qubits.first()?;
            Some(format!("qc.ry({:.6}, {})", theta, target))
        }
        GateType::Rz(theta) => {
            let target = gate.target_qubits.first()?;
            Some(format!("qc.rz({:.6}, {})", theta, target))
        }

        // Controlled gates
        GateType::Cnot => {
            let control = gate.control_qubits.first()?;
            let target = gate.target_qubits.first()?;
            Some(format!("qc.cx({}, {})", control, target))
        }
        GateType::Cz => {
            let control = gate.control_qubits.first()?;
            let target = gate.target_qubits.first()?;
            Some(format!("qc.cz({}, {})", control, target))
        }

        // Multi-qubit gates
        GateType::Swap => {
            let q1 = gate.target_qubits.get(0)?;
            let q2 = gate.target_qubits.get(1)?;
            Some(format!("qc.swap({}, {})", q1, q2))
        }
        GateType::Toffoli => {
            let ctrl1 = gate.control_qubits.get(0)?;
            let ctrl2 = gate.control_qubits.get(1)?;
            let target = gate.target_qubits.first()?;
            Some(format!("qc.ccx({}, {}, {})", ctrl1, ctrl2, target))
        }

        // Meta gates
        GateType::Barrier => {
            let qubits: Vec<String> = gate
                .target_qubits
                .iter()
                .map(|q| q.to_string())
                .collect();
            Some(format!("qc.barrier([{}])", qubits.join(", ")))
        }

        // Identity / no-op - skip
        GateType::Identity => None,

        // Custom gates - generate as comment
        GateType::Custom(name) => {
            let target = gate.target_qubits.first()?;
            Some(format!(
                "# Custom gate: {} on qubit {} (requires manual implementation)",
                name, target
            ))
        }
    }
}

impl Circuit {
    /// Export this circuit to Qiskit Python code.
    ///
    /// # Returns
    /// * `Ok(String)` - The generated Python code.
    /// * `Err(QiskitError)` - If the circuit cannot be exported.
    ///
    /// # Example
    /// ```no_run
    /// use ketgrid_core::Circuit;
    ///
    /// let circuit = Circuit::new(2);
    /// let python_code = circuit.to_qiskit().unwrap();
    /// println!("{}", python_code);
    /// ```
    pub fn to_qiskit(&self) -> Result<String, QiskitError> {
        circuit_to_qiskit(self)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gate::GateType;

    #[test]
    fn test_empty_circuit_error() {
        let circuit = Circuit::new(0);
        let result = circuit_to_qiskit(&circuit);
        assert!(result.is_err());
        assert_eq!(result.unwrap_err(), QiskitError::EmptyCircuit);
    }

    #[test]
    fn test_single_qubit_gates() {
        let mut circuit = Circuit::new(1);
        circuit.add_gate(GateType::H, vec![0], vec![], 0).unwrap();
        circuit.add_gate(GateType::X, vec![0], vec![], 1).unwrap();
        circuit.add_gate(GateType::Y, vec![0], vec![], 2).unwrap();
        circuit.add_gate(GateType::Z, vec![0], vec![], 3).unwrap();
        circuit.add_gate(GateType::S, vec![0], vec![], 4).unwrap();
        circuit.add_gate(GateType::T, vec![0], vec![], 5).unwrap();

        let code = circuit_to_qiskit(&circuit).unwrap();
        assert!(code.contains("qc.h(0)"));
        assert!(code.contains("qc.x(0)"));
        assert!(code.contains("qc.y(0)"));
        assert!(code.contains("qc.z(0)"));
        assert!(code.contains("qc.s(0)"));
        assert!(code.contains("qc.t(0)"));
    }

    #[test]
    fn test_parameterized_gates() {
        let mut circuit = Circuit::new(2);
        circuit
            .add_gate(GateType::Rx(std::f64::consts::PI), vec![0], vec![], 0)
            .unwrap();
        circuit
            .add_gate(GateType::Ry(std::f64::consts::FRAC_PI_2), vec![1], vec![], 1)
            .unwrap();
        circuit.add_gate(GateType::Rz(1.0), vec![0], vec![], 2).unwrap();

        let code = circuit_to_qiskit(&circuit).unwrap();
        assert!(code.contains("qc.rx(3.141593, 0)"));
        assert!(code.contains("qc.ry(1.570796, 1)"));
        assert!(code.contains("qc.rz(1.000000, 0)"));
    }

    #[test]
    fn test_controlled_gates() {
        let mut circuit = Circuit::new(2);
        circuit.add_gate(GateType::Cnot, vec![1], vec![0], 0).unwrap();

        let code = circuit_to_qiskit(&circuit).unwrap();
        assert!(code.contains("qc.cx(0, 1)"));
    }

    #[test]
    fn test_cz_gate() {
        let mut circuit = Circuit::new(2);
        circuit.add_gate(GateType::Cz, vec![1], vec![0], 0).unwrap();

        let code = circuit_to_qiskit(&circuit).unwrap();
        assert!(code.contains("qc.cz(0, 1)"));
    }

    #[test]
    fn test_swap_gate() {
        let mut circuit = Circuit::new(2);
        circuit.add_gate(GateType::Swap, vec![0, 1], vec![], 0).unwrap();

        let code = circuit_to_qiskit(&circuit).unwrap();
        assert!(code.contains("qc.swap(0, 1)"));
    }

    #[test]
    fn test_toffoli_gate() {
        let mut circuit = Circuit::new(3);
        circuit.add_gate(GateType::Toffoli, vec![2], vec![0, 1], 0).unwrap();

        let code = circuit_to_qiskit(&circuit).unwrap();
        assert!(code.contains("qc.ccx(0, 1, 2)"));
    }

    #[test]
    fn test_barrier_gate() {
        let mut circuit = Circuit::new(2);
        circuit.add_gate(GateType::Barrier, vec![0], vec![], 0).unwrap();
        circuit.add_gate(GateType::Barrier, vec![1], vec![], 0).unwrap();

        let code = circuit_to_qiskit(&circuit).unwrap();
        assert!(code.contains("qc.barrier([0])"));
        assert!(code.contains("qc.barrier([1])"));
    }

    #[test]
    fn test_barrier_gate_single_qubit() {
        let mut circuit = Circuit::new(1);
        circuit.add_gate(GateType::H, vec![0], vec![], 0).unwrap();
        circuit.add_gate(GateType::Barrier, vec![0], vec![], 1).unwrap();
        circuit.add_gate(GateType::X, vec![0], vec![], 2).unwrap();

        let code = circuit_to_qiskit(&circuit).unwrap();
        // Barrier should appear between H and X
        let h_pos = code.find("qc.h(0)").unwrap();
        let barrier_pos = code.find("qc.barrier([0])").unwrap();
        let x_pos = code.find("qc.x(0)").unwrap();
        assert!(h_pos < barrier_pos, "H should come before barrier");
        assert!(barrier_pos < x_pos, "barrier should come before X");
    }

    #[test]
    fn test_identity_gate_skipped() {
        let mut circuit = Circuit::new(1);
        circuit.add_gate(GateType::H, vec![0], vec![], 0).unwrap();
        circuit.add_gate(GateType::Identity, vec![0], vec![], 1).unwrap();
        circuit.add_gate(GateType::X, vec![0], vec![], 2).unwrap();

        let code = circuit_to_qiskit(&circuit).unwrap();
        // Identity should be skipped (no line generated)
        assert!(code.contains("qc.h(0)"));
        assert!(code.contains("qc.x(0)"));
        // The code should not contain any reference to Identity
        assert!(!code.contains("Identity"));
    }

    #[test]
    fn test_custom_gate_comment() {
        let mut circuit = Circuit::new(1);
        circuit
            .add_gate(GateType::Custom("U3Gate".to_string()), vec![0], vec![], 0)
            .unwrap();

        let code = circuit_to_qiskit(&circuit).unwrap();
        assert!(code.contains("# Custom gate: U3Gate"));
    }

    #[test]
    fn test_measurements() {
        let mut circuit = Circuit::new(2);
        circuit.add_gate(GateType::H, vec![0], vec![], 0).unwrap();
        circuit.add_measurement(0, 1).unwrap();
        circuit.add_measurement(1, 1).unwrap();

        let code = circuit_to_qiskit(&circuit).unwrap();
        // Should have classical bits
        assert!(code.contains("QuantumCircuit(2, 2)"));
        // Should have measurement lines
        assert!(code.contains("qc.measure(0, 0)"));
        assert!(code.contains("qc.measure(1, 1)"));
    }

    #[test]
    fn test_bell_state_circuit() {
        let mut circuit = Circuit::new(2);
        circuit.add_gate(GateType::H, vec![0], vec![], 0).unwrap();
        circuit.add_gate(GateType::Cnot, vec![1], vec![0], 1).unwrap();
        circuit.add_measurement(0, 2).unwrap();
        circuit.add_measurement(1, 2).unwrap();

        let code = circuit_to_qiskit(&circuit).unwrap();

        // Check header
        assert!(code.contains("from qiskit import QuantumCircuit"));

        // Check circuit creation
        assert!(code.contains("qc = QuantumCircuit(2, 2)"));

        // Check gate order (should be sorted by column)
        let h_pos = code.find("qc.h(0)").unwrap();
        let cx_pos = code.find("qc.cx(0, 1)").unwrap();
        assert!(h_pos < cx_pos, "H gate should come before CNOT");

        // Check measurements
        assert!(code.contains("qc.measure(0, 0)"));
        assert!(code.contains("qc.measure(1, 1)"));
    }

    #[test]
    fn test_circuit_to_qiskit_method() {
        let mut circuit = Circuit::new(1);
        circuit.add_gate(GateType::H, vec![0], vec![], 0).unwrap();

        let code = circuit.to_qiskit().unwrap();
        assert!(code.contains("qc.h(0)"));
    }

    #[test]
    fn test_execution_order_by_column() {
        // Gates added out of order should be sorted by column in output
        let mut circuit = Circuit::new(2);
        circuit.add_gate(GateType::X, vec![1], vec![], 2).unwrap();
        circuit.add_gate(GateType::H, vec![0], vec![], 0).unwrap();
        circuit.add_gate(GateType::Z, vec![0], vec![], 1).unwrap();

        let code = circuit_to_qiskit(&circuit).unwrap();

        // Find positions
        let h_pos = code.find("qc.h(0)").unwrap();
        let z_pos = code.find("qc.z(0)").unwrap();
        let x_pos = code.find("qc.x(1)").unwrap();

        // Should be in column order: H (col 0), Z (col 1), X (col 2)
        assert!(h_pos < z_pos, "H should come before Z");
        assert!(z_pos < x_pos, "Z should come before X");
    }

    #[test]
    fn test_qiskit_runner_comments() {
        let circuit = Circuit::new(1);
        let code = circuit_to_qiskit(&circuit).unwrap();

        // Should include example execution code as comments
        assert!(code.contains("from qiskit import transpile, Aer"));
        assert!(code.contains("simulator = Aer.get_backend('aer_simulator')"));
        assert!(code.contains("result.get_counts()"));
    }
}
