//! SVG vector export for quantum circuits.
//!
//! This module exports KetGrid circuits to publication-quality SVG figures
//! suitable for academic papers, presentations, and documentation.

use crate::circuit::{Circuit, Measurement, PlacedGate};
use crate::gate::GateType;

/// Error type for SVG export operations.
#[derive(Debug, Clone, PartialEq)]
pub enum SvgError {
    /// Circuit has no qubits.
    EmptyCircuit,
    /// Invalid gate configuration.
    InvalidGate(String),
}

impl std::fmt::Display for SvgError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SvgError::EmptyCircuit => write!(f, "Cannot export empty circuit (no qubits)"),
            SvgError::InvalidGate(msg) => write!(f, "Invalid gate configuration: {}", msg),
        }
    }
}

impl std::error::Error for SvgError {}

// Layout constants (matching circuit_view.rs)
const WIRE_SPACING: f32 = 60.0;
const WIRE_MARGIN_TOP: f32 = 40.0;
const LABEL_WIDTH: f32 = 55.0;
const COLUMN_WIDTH: f32 = 64.0;
const GATE_BOX_SIZE: f32 = 36.0;
const CONTROL_DOT_RADIUS: f32 = 5.0;
const TARGET_CIRCLE_RADIUS: f32 = 14.0;
const SWAP_CROSS_SIZE: f32 = 8.0;
const MEASUREMENT_BOX_SIZE: f32 = 32.0;
const WIRE_START_OFFSET: f32 = 20.0;
const RIGHT_MARGIN: f32 = 30.0;

/// SVG styling colors (publication-ready dark-on-light theme).
struct SvgColors {
    background: &'static str,
    wire: &'static str,
    gate_fill: &'static str,
    gate_stroke: &'static str,
    text: &'static str,
    control_dot: &'static str,
    measurement_fill: &'static str,
}

impl Default for SvgColors {
    fn default() -> Self {
        Self {
            background: "#ffffff",
            wire: "#333333",
            gate_fill: "#f8f9fa",
            gate_stroke: "#495057",
            text: "#212529",
            control_dot: "#212529",
            measurement_fill: "#f8f9fa",
        }
    }
}

/// Generate SVG for a quantum circuit.
///
/// Creates a publication-quality SVG with proper scaling for A4 pages.
/// The SVG includes qubit wire labels, all gates, and measurements.
///
/// # Arguments
/// * `circuit` - The circuit to export.
///
/// # Returns
/// * `Ok(String)` - The generated SVG XML.
/// * `Err(SvgError)` - If the circuit cannot be exported.
///
/// # Example
/// ```
/// use ketgrid_core::{Circuit, GateType};
/// use ketgrid_core::format::svg::circuit_to_svg;
///
/// let mut circuit = Circuit::new(2);
/// circuit.add_gate(GateType::H, vec![0], vec![], 0).unwrap();
/// circuit.add_gate(GateType::Cnot, vec![1], vec![0], 1).unwrap();
///
/// let svg = circuit_to_svg(&circuit).unwrap();
/// assert!(svg.contains("<svg"));
/// assert!(svg.contains("</svg>"));
/// ```
pub fn circuit_to_svg(circuit: &Circuit) -> Result<String, SvgError> {
    if circuit.num_qubits() == 0 {
        return Err(SvgError::EmptyCircuit);
    }

    let colors = SvgColors::default();
    let svg = SvgGenerator::new(circuit, &colors);
    Ok(svg.generate())
}

/// SVG generator that mirrors circuit_view.rs rendering logic.
struct SvgGenerator<'a> {
    circuit: &'a Circuit,
    colors: &'a SvgColors,
}

impl<'a> SvgGenerator<'a> {
    fn new(circuit: &'a Circuit, colors: &'a SvgColors) -> Self {
        Self { circuit, colors }
    }

    fn generate(&self) -> String {
        let num_qubits = self.circuit.num_qubits();
        let max_column = self.circuit.max_column();
        let num_columns = max_column + 1;

        // Calculate dimensions
        let width = LABEL_WIDTH + WIRE_START_OFFSET + (num_columns as f32 * COLUMN_WIDTH) + RIGHT_MARGIN;
        let height = WIRE_MARGIN_TOP + (num_qubits as f32 * WIRE_SPACING) + WIRE_MARGIN_TOP;

        let mut svg = String::new();

        // SVG header with A4-optimized viewBox
        svg.push_str(&format!(
            r#"<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {:.1} {:.1}" preserveAspectRatio="xMidYMid meet">
  <title>Quantum Circuit</title>
  <desc>Generated by KetGrid - Quantum Circuit SVG Export</desc>
  <defs>
    <style>
      .wire {{ stroke: {}; stroke-width: 1.5; fill: none; }}
      .gate-box {{ fill: {}; stroke: {}; stroke-width: 1.5; }}
      .gate-text {{ font-family: system-ui, -apple-system, sans-serif; font-size: 13px; fill: {}; text-anchor: middle; dominant-baseline: central; }}
      .qubit-label {{ font-family: system-ui, -apple-system, sans-serif; font-size: 14px; fill: {}; text-anchor: start; dominant-baseline: central; }}
      .control-dot {{ fill: {}; }}
      .target-circle {{ fill: none; stroke: {}; stroke-width: 2; }}
      .cross {{ stroke: {}; stroke-width: 2; }}
      .measurement-box {{ fill: {}; stroke: {}; stroke-width: 1.5; }}
      .arc {{ fill: none; stroke: {}; stroke-width: 1.5; }}
      .vertical-line {{ stroke: {}; stroke-width: 2; }}
    </style>
  </defs>
  <rect width="100%" height="100%" fill="{}"/>
"#,
            width, height,
            self.colors.wire,
            self.colors.gate_fill, self.colors.gate_stroke, self.colors.text,
            self.colors.text,
            self.colors.control_dot,
            self.colors.wire,
            self.colors.wire,
            self.colors.measurement_fill, self.colors.gate_stroke,
            self.colors.wire,
            self.colors.wire,
            self.colors.background
        ));

        // Draw qubit wires and labels
        for qubit_idx in 0..num_qubits {
            self.draw_wire(&mut svg, qubit_idx, width);
        }

        // Draw gates
        for gate in &self.circuit.gates {
            self.draw_gate(&mut svg, gate);
        }

        // Draw measurements
        for measurement in &self.circuit.measurements {
            self.draw_measurement(&mut svg, measurement);
        }

        // SVG footer
        svg.push_str("</svg>\n");

        svg
    }

    fn wire_y(&self, qubit_idx: usize) -> f32 {
        WIRE_MARGIN_TOP + qubit_idx as f32 * WIRE_SPACING
    }

    fn column_x(&self, column: usize) -> f32 {
        LABEL_WIDTH + WIRE_START_OFFSET + column as f32 * COLUMN_WIDTH + COLUMN_WIDTH / 2.0
    }

    fn draw_wire(&self, svg: &mut String, qubit_idx: usize, width: f32) {
        let y = self.wire_y(qubit_idx);
        let label = &self.circuit.qubits[qubit_idx].label;

        // Wire label
        svg.push_str(&format!(
            r#"  <text x="8" y="{:.1}" class="qubit-label">{}</text>
"#,
            y,
            Self::escape_xml(label)
        ));

        // Horizontal wire line
        let wire_start = LABEL_WIDTH + WIRE_START_OFFSET - 10.0;
        let wire_end = width - RIGHT_MARGIN + 10.0;
        svg.push_str(&format!(
            r#"  <line x1="{:.1}" y1="{:.1}" x2="{:.1}" y2="{:.1}" class="wire"/>
"#,
            wire_start, y, wire_end, y
        ));
    }

    fn draw_gate(&self, svg: &mut String, gate: &PlacedGate) {
        let cx = self.column_x(gate.column);

        match &gate.gate {
            GateType::Cnot | GateType::Toffoli => {
                self.draw_controlled_not(svg, gate, cx);
            }
            GateType::Cz => {
                self.draw_cz(svg, gate, cx);
            }
            GateType::Swap => {
                self.draw_swap(svg, gate, cx);
            }
            GateType::Barrier => {
                self.draw_barrier(svg, gate, cx);
            }
            _ => {
                if let Some(&target_q) = gate.target_qubits.first() {
                    let cy = self.wire_y(target_q);
                    let label = self.gate_display_label(&gate.gate);
                    self.draw_gate_box(svg, cx, cy, &label);
                }
            }
        }
    }

    fn draw_gate_box(&self, svg: &mut String, cx: f32, cy: f32, label: &str) {
        let width = if label.len() > 3 {
            GATE_BOX_SIZE + 16.0
        } else {
            GATE_BOX_SIZE
        };
        let height = GATE_BOX_SIZE;
        let half_w = width / 2.0;
        let half_h = height / 2.0;

        // Rounded rectangle for gate
        svg.push_str(&format!(
            r#"  <rect x="{:.1}" y="{:.1}" width="{:.1}" height="{:.1}" rx="4" ry="4" class="gate-box"/>
"#,
            cx - half_w,
            cy - half_h,
            width,
            height
        ));

        // Gate label
        svg.push_str(&format!(
            r#"  <text x="{:.1}" y="{:.1}" class="gate-text">{}</text>
"#,
            cx, cy, Self::escape_xml(label)
        ));
    }

    fn draw_controlled_not(&self, svg: &mut String, gate: &PlacedGate, cx: f32) {
        let all = gate.all_qubits();
        let (min_q, max_q) = qubit_extent(&all);

        let y_top = self.wire_y(min_q);
        let y_bot = self.wire_y(max_q);

        // Vertical connecting line
        svg.push_str(&format!(
            r#"  <line x1="{:.1}" y1="{:.1}" x2="{:.1}" y2="{:.1}" class="vertical-line"/>
"#,
            cx, y_top, cx, y_bot
        ));

        // Control dots
        for &q in &gate.control_qubits {
            let cy = self.wire_y(q);
            svg.push_str(&format!(
                r#"  <circle cx="{:.1}" cy="{:.1}" r="{}" class="control-dot"/>
"#,
                cx, cy, CONTROL_DOT_RADIUS
            ));
        }

        // Target circles (⊕)
        for &q in &gate.target_qubits {
            let cy = self.wire_y(q);
            // Circle
            svg.push_str(&format!(
                r#"  <circle cx="{:.1}" cy="{:.1}" r="{}" class="target-circle"/>
"#,
                cx, cy, TARGET_CIRCLE_RADIUS
            ));
            // Horizontal line of +
            svg.push_str(&format!(
                r#"  <line x1="{:.1}" y1="{:.1}" x2="{:.1}" y2="{:.1}" class="cross"/>
"#,
                cx - TARGET_CIRCLE_RADIUS,
                cy,
                cx + TARGET_CIRCLE_RADIUS,
                cy
            ));
            // Vertical line of +
            svg.push_str(&format!(
                r#"  <line x1="{:.1}" y1="{:.1}" x2="{:.1}" y2="{:.1}" class="cross"/>
"#,
                cx,
                cy - TARGET_CIRCLE_RADIUS,
                cx,
                cy + TARGET_CIRCLE_RADIUS
            ));
        }
    }

    fn draw_cz(&self, svg: &mut String, gate: &PlacedGate, cx: f32) {
        let all = gate.all_qubits();
        let (min_q, max_q) = qubit_extent(&all);

        let y_top = self.wire_y(min_q);
        let y_bot = self.wire_y(max_q);

        // Vertical connecting line
        svg.push_str(&format!(
            r#"  <line x1="{:.1}" y1="{:.1}" x2="{:.1}" y2="{:.1}" class="vertical-line"/>
"#,
            cx, y_top, cx, y_bot
        ));

        // Control dots on all qubits
        for &q in all.iter() {
            let cy = self.wire_y(q);
            svg.push_str(&format!(
                r#"  <circle cx="{:.1}" cy="{:.1}" r="{}" class="control-dot"/>
"#,
                cx, cy, CONTROL_DOT_RADIUS
            ));
        }
    }

    fn draw_swap(&self, svg: &mut String, gate: &PlacedGate, cx: f32) {
        let (min_q, max_q) = qubit_extent(&gate.target_qubits);

        let y_top = self.wire_y(min_q);
        let y_bot = self.wire_y(max_q);

        // Vertical connecting line
        svg.push_str(&format!(
            r#"  <line x1="{:.1}" y1="{:.1}" x2="{:.1}" y2="{:.1}" class="vertical-line"/>
"#,
            cx, y_top, cx, y_bot
        ));

        // Cross marks on each target qubit
        for &q in &gate.target_qubits {
            let cy = self.wire_y(q);
            let s = SWAP_CROSS_SIZE;
            // First diagonal
            svg.push_str(&format!(
                r#"  <line x1="{:.1}" y1="{:.1}" x2="{:.1}" y2="{:.1}" class="cross"/>
"#,
                cx - s, cy - s, cx + s, cy + s
            ));
            // Second diagonal
            svg.push_str(&format!(
                r#"  <line x1="{:.1}" y1="{:.1}" x2="{:.1}" y2="{:.1}" class="cross"/>
"#,
                cx + s, cy - s, cx - s, cy + s
            ));
        }
    }

    fn draw_barrier(&self, svg: &mut String, gate: &PlacedGate, cx: f32) {
        for &q in &gate.target_qubits {
            let y = self.wire_y(q);
            let half = WIRE_SPACING / 2.0;
            let dash_len = 4.0;
            let color = self.colors.wire;

            let mut py = y - half;
            let end_y = y + half;
            while py < end_y {
                let seg_end = (py + dash_len).min(end_y);
                svg.push_str(&format!(
                    r#"  <line x1="{:.1}" y1="{:.1}" x2="{:.1}" y2="{:.1}" stroke="{}" stroke-width="1.5" stroke-dasharray="3,3"/>
"#,
                    cx, py, cx, seg_end, color
                ));
                py += dash_len * 2.0;
            }
        }
    }

    fn draw_measurement(&self, svg: &mut String, measurement: &Measurement) {
        if measurement.qubit_id >= self.circuit.num_qubits() {
            return;
        }

        let cx = self.column_x(measurement.column);
        let cy = self.wire_y(measurement.qubit_id);
        let s = MEASUREMENT_BOX_SIZE / 2.0;

        // Measurement box
        svg.push_str(&format!(
            r#"  <rect x="{:.1}" y="{:.1}" width="{}" height="{}" rx="3" ry="3" class="measurement-box"/>
"#,
            cx - s,
            cy - s,
            MEASUREMENT_BOX_SIZE,
            MEASUREMENT_BOX_SIZE
        ));

        // Semicircular arc (meter symbol) - approximated with path
        let arc_center_y = cy + s * 0.15;
        let arc_radius = s * 0.55;

        // Draw arc as a path
        svg.push_str(&format!(
            r#"  <path d="M {:.1} {:.1} A {} {} 0 0 1 {:.1} {:.1}" class="arc"/>
"#,
            cx - arc_radius,
            arc_center_y,
            arc_radius,
            arc_radius,
            cx + arc_radius,
            arc_center_y
        ));

        // Arrow from center to top-right
        let arrow_end_x = cx + s * 0.45;
        let arrow_end_y = cy - s * 0.45;
        svg.push_str(&format!(
            r#"  <line x1="{:.1}" y1="{:.1}" x2="{:.1}" y2="{:.1}" class="cross"/>
"#,
            cx, arc_center_y, arrow_end_x, arrow_end_y
        ));
    }

    fn gate_display_label(&self, gate: &GateType) -> String {
        match gate {
            GateType::Rx(theta) => format!("Rx({:.1})", theta),
            GateType::Ry(theta) => format!("Ry({:.1})", theta),
            GateType::Rz(theta) => format!("Rz({:.1})", theta),
            GateType::Cnot | GateType::Toffoli => "+".to_string(),
            _ => gate.display_name(),
        }
    }

    /// Escape special XML characters in text.
    fn escape_xml(text: &str) -> String {
        text.replace('&', "&amp;")
            .replace('<', "&lt;")
            .replace('>', "&gt;")
            .replace('"', "&quot;")
            .replace('\'', "&apos;")
    }
}

fn qubit_extent(qubits: &[usize]) -> (usize, usize) {
    let min = qubits.iter().copied().min().unwrap_or(0);
    let max = qubits.iter().copied().max().unwrap_or(0);
    (min, max)
}

impl Circuit {
    /// Export this circuit to SVG format.
    ///
    /// # Returns
    /// * `Ok(String)` - The generated SVG XML.
    /// * `Err(SvgError)` - If the circuit cannot be exported.
    ///
    /// # Example
    /// ```no_run
    /// use ketgrid_core::Circuit;
    ///
    /// let circuit = Circuit::new(2);
    /// let svg = circuit.to_svg().unwrap();
    /// println!("{}", svg);
    /// ```
    pub fn to_svg(&self) -> Result<String, SvgError> {
        circuit_to_svg(self)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gate::GateType;

    #[test]
    fn test_empty_circuit_error() {
        let circuit = Circuit::new(0);
        let result = circuit_to_svg(&circuit);
        assert!(result.is_err());
        assert_eq!(result.unwrap_err(), SvgError::EmptyCircuit);
    }

    #[test]
    fn test_svg_header_structure() {
        let circuit = Circuit::new(2);
        let svg = circuit_to_svg(&circuit).unwrap();

        // Basic SVG structure
        assert!(svg.contains(r#"<?xml version="1.0" encoding="UTF-8"?>"#));
        assert!(svg.contains("<svg"));
        assert!(svg.contains("</svg>"));
        assert!(svg.contains("xmlns=\"http://www.w3.org/2000/svg\""));
        assert!(svg.contains("viewBox"));
        assert!(svg.contains("preserveAspectRatio"));
    }

    #[test]
    fn test_wire_rendering() {
        let mut circuit = Circuit::new(3);
        circuit.qubits[0].label = "|q₀⟩".to_string();
        circuit.qubits[1].label = "|q₁⟩".to_string();
        circuit.qubits[2].label = "|q₂⟩".to_string();

        let svg = circuit_to_svg(&circuit).unwrap();

        // Should have 3 qubit labels
        assert!(svg.contains("|q₀⟩"));
        assert!(svg.contains("|q₁⟩"));
        assert!(svg.contains("|q₂⟩"));

        // Should have wire lines
        assert!(svg.contains("<line"));
        assert!(svg.contains("class=\"wire\""));
    }

    #[test]
    fn test_single_qubit_gates() {
        let mut circuit = Circuit::new(1);
        circuit.add_gate(GateType::H, vec![0], vec![], 0).unwrap();
        circuit.add_gate(GateType::X, vec![0], vec![], 1).unwrap();

        let svg = circuit_to_svg(&circuit).unwrap();

        // Should contain gate boxes
        assert!(svg.contains("class=\"gate-box\""));
        assert!(svg.contains("H"));
        assert!(svg.contains("X"));
    }

    #[test]
    fn test_parameterized_gates() {
        let mut circuit = Circuit::new(1);
        circuit
            .add_gate(GateType::Rx(std::f64::consts::PI), vec![0], vec![], 0)
            .unwrap();

        let svg = circuit_to_svg(&circuit).unwrap();
        assert!(svg.contains("Rx"));
    }

    #[test]
    fn test_cnot_gate() {
        let mut circuit = Circuit::new(2);
        circuit.add_gate(GateType::Cnot, vec![1], vec![0], 0).unwrap();

        let svg = circuit_to_svg(&circuit).unwrap();

        // Should have control dot, target circle, and connecting line
        assert!(svg.contains("class=\"control-dot\""));
        assert!(svg.contains("class=\"target-circle\""));
        assert!(svg.contains("class=\"vertical-line\""));
    }

    #[test]
    fn test_cz_gate() {
        let mut circuit = Circuit::new(2);
        circuit.add_gate(GateType::Cz, vec![1], vec![0], 0).unwrap();

        let svg = circuit_to_svg(&circuit).unwrap();

        // Should have two control dots and connecting line
        assert!(svg.contains("class=\"control-dot\""));
        assert!(svg.contains("class=\"vertical-line\""));
    }

    #[test]
    fn test_swap_gate() {
        let mut circuit = Circuit::new(2);
        circuit.add_gate(GateType::Swap, vec![0, 1], vec![], 0).unwrap();

        let svg = circuit_to_svg(&circuit).unwrap();

        // Should have cross marks and connecting line
        assert!(svg.contains("class=\"cross\""));
        assert!(svg.contains("class=\"vertical-line\""));
    }

    #[test]
    fn test_toffoli_gate() {
        let mut circuit = Circuit::new(3);
        circuit
            .add_gate(GateType::Toffoli, vec![2], vec![0, 1], 0)
            .unwrap();

        let svg = circuit_to_svg(&circuit).unwrap();

        // Should have two control dots, one target circle
        assert!(svg.contains("class=\"control-dot\""));
        assert!(svg.contains("class=\"target-circle\""));
    }

    #[test]
    fn test_barrier_gate() {
        let mut circuit = Circuit::new(2);
        circuit.add_gate(GateType::Barrier, vec![0], vec![], 0).unwrap();
        circuit.add_gate(GateType::Barrier, vec![1], vec![], 0).unwrap();

        let svg = circuit_to_svg(&circuit).unwrap();

        // Should contain dashed line
        assert!(svg.contains("stroke-dasharray"));
    }

    #[test]
    fn test_measurement_rendering() {
        let mut circuit = Circuit::new(1);
        circuit.add_measurement(0, 0).unwrap();

        let svg = circuit_to_svg(&circuit).unwrap();

        // Should have measurement box and arc
        assert!(svg.contains("class=\"measurement-box\""));
        assert!(svg.contains("class=\"arc\""));
    }

    #[test]
    fn test_bell_state_circuit() {
        let mut circuit = Circuit::new(2);
        circuit.add_gate(GateType::H, vec![0], vec![], 0).unwrap();
        circuit.add_gate(GateType::Cnot, vec![1], vec![0], 1).unwrap();

        let svg = circuit_to_svg(&circuit).unwrap();

        // Should have H gate, CNOT components
        assert!(svg.contains("H"));
        assert!(svg.contains("class=\"control-dot\""));
        assert!(svg.contains("class=\"target-circle\""));
    }

    #[test]
    fn test_escape_xml() {
        let mut circuit = Circuit::new(1);
        circuit.qubits[0].label = "<test> & \"value\"".to_string();

        let svg = circuit_to_svg(&circuit).unwrap();

        // Special characters should be escaped
        assert!(!svg.contains("<test>"));
        assert!(svg.contains("&lt;test&gt;"));
        assert!(svg.contains("&amp;"));
        assert!(svg.contains("&quot;value&quot;"));
    }

    #[test]
    fn test_circuit_to_svg_method() {
        let mut circuit = Circuit::new(1);
        circuit.add_gate(GateType::H, vec![0], vec![], 0).unwrap();

        let svg = circuit.to_svg().unwrap();
        assert!(svg.contains("<svg"));
        assert!(svg.contains("H"));
    }
}
